-- Add a theme entry here after installing variants for every configured app.
-- Theme IDs also name each theme's asset directory.
return {
    web = {
        label = "Web",
        colorscheme = "web",
        ghostty = { light = "web-light", dark = "web-dark" },
        yazi = { light = "web-light", dark = "web-dark" },
        palette = {
            light = {
                roles = {
                    background = "#ffffff",
                    surface = "#f3f4f6",
                    text = "#000000",
                    muted = "#5b616e",
                    border = "#d1d5db",
                    selection = "#e5e7eb",
                    link = "#0000ee",
                    visited = "#551a8b",
                    active = "#ff0000",
                    error = "#b00020",
                    warning = "#8a4b00",
                    success = "#008000",
                    string = "#008000",
                    number = "#8a4b00",
                    keyword = "#551a8b",
                    type = "#006a70",
                    func = "#0000ee",
                    constant = "#a31515",
                    variable = "#000000",
                    operator = "#000000",
                },
            },
            dark = {
                roles = {
                    background = "#111111",
                    surface = "#1c1c1c",
                    text = "#f5f5f5",
                    muted = "#b4b4b4",
                    border = "#4b5563",
                    selection = "#30363d",
                    link = "#8ab4f8",
                    visited = "#d2a8ff",
                    active = "#ff7b72",
                    error = "#ff7b72",
                    warning = "#f2cc60",
                    success = "#3fb950",
                    string = "#7ee787",
                    number = "#f2cc60",
                    keyword = "#d2a8ff",
                    type = "#56d4dd",
                    func = "#8ab4f8",
                    constant = "#ffa198",
                    variable = "#f5f5f5",
                    operator = "#c9d1d9",
                },
            },
        },
    },
}
