set -g @theme_bg "#000000"
set -g @theme_fg "#c6c6c6"
set -g @theme_muted "#4e4e4e"
set -g @theme_accent "#d75f87"
set -g @theme_branch "#767676"
set -g @theme_git "#5fd7a7"
set -g @theme_time "#a8a8a8"
set -g @theme_border "#767676"
set -g @theme_pane_active "#d75f87"
