set -g @theme_bg "#ffffff"
set -g @theme_fg "#262626"
set -g @theme_muted "#767676"
set -g @theme_accent "#ff5f87"
set -g @theme_branch "#767676"
set -g @theme_git "#10a778"
set -g @theme_time "#5f4b00"
set -g @theme_border "#a8a8a8"
set -g @theme_pane_active "#d75f87"
