local switcher_dir = vim.fn.stdpath("config"):gsub("/nvim$", "") .. "/theme-switcher"
local active_theme_lines = vim.fn.readfile(switcher_dir .. "/current", "", 1)
local active_theme_id = active_theme_lines[1] or "web"
local themes = dofile(switcher_dir .. "/themes.lua")
local theme = assert(themes[active_theme_id], "Unknown theme: " .. active_theme_id)
local mode_palette = assert(theme.palette[vim.o.background], "Missing palette for " .. vim.o.background)
local colors = assert(mode_palette.roles, "Missing semantic colors for " .. vim.o.background)
local base16_palette = {
    base00 = colors.background,
    base01 = colors.surface,
    base02 = colors.selection,
    base03 = colors.muted,
    base04 = colors.operator,
    base05 = colors.text,
    base06 = colors.text,
    base07 = colors.text,
    base08 = colors.error,
    base09 = colors.number,
    base0A = colors.warning,
    base0B = colors.string,
    base0C = colors.type,
    base0D = colors.link,
    base0E = colors.keyword,
    base0F = colors.constant,
}

require("mini.base16").setup({
    palette = base16_palette,
    plugins = {
        default = false,
        ["nvim-mini/mini.nvim"] = true,
        ["akinsho/bufferline.nvim"] = true,
        ["lewis6991/gitsigns.nvim"] = true,
        ["nvim-lualine/lualine.nvim"] = true,
        ["nvim-neo-tree/neo-tree.nvim"] = true,
        ["nvim-telescope/telescope.nvim"] = true,
        ["MeanderingProgrammer/render-markdown.nvim"] = true,
    },
})

local highlights = {
    Normal = { fg = colors.text, bg = colors.background },
    NormalNC = { fg = colors.text, bg = colors.background },
    NormalFloat = { fg = colors.text, bg = colors.surface },
    FloatBorder = { fg = colors.border, bg = colors.surface },
    ColorColumn = { bg = colors.surface },
    CursorLine = { bg = colors.selection },
    CursorColumn = { bg = colors.selection },
    Visual = { bg = colors.selection },
    Search = { fg = colors.text, bg = colors.selection },
    IncSearch = { fg = colors.background, bg = colors.active, bold = true },
    CurSearch = { fg = colors.background, bg = colors.active, bold = true },
    MatchParen = { fg = colors.active, bold = true, underline = true },
    LineNr = { fg = colors.muted },
    CursorLineNr = { fg = colors.active, bold = true },
    SignColumn = { fg = colors.muted, bg = colors.background },
    Folded = { fg = colors.muted, bg = colors.surface },
    FoldColumn = { fg = colors.muted, bg = colors.background },
    EndOfBuffer = { fg = colors.muted },
    VertSplit = { fg = colors.border },
    WinSeparator = { fg = colors.border },
    StatusLine = { fg = colors.text, bg = colors.surface },
    StatusLineNC = { fg = colors.muted, bg = colors.surface },
    MsgArea = { fg = colors.text },
    MsgSeparator = { fg = colors.border, bg = colors.surface },
    Pmenu = { fg = colors.text, bg = colors.surface },
    PmenuSel = { fg = colors.text, bg = colors.selection, bold = true },
    PmenuSbar = { bg = colors.selection },
    PmenuThumb = { bg = colors.muted },
    Comment = { fg = colors.muted, italic = true },
    Constant = { fg = colors.constant },
    String = { fg = colors.string },
    Character = { fg = colors.string },
    Number = { fg = colors.number },
    Boolean = { fg = colors.number },
    Float = { fg = colors.number },
    Identifier = { fg = colors.variable },
    Function = { fg = colors.func, bold = true },
    Statement = { fg = colors.keyword, bold = true },
    Conditional = { fg = colors.keyword, bold = true },
    Repeat = { fg = colors.keyword, bold = true },
    Label = { fg = colors.keyword },
    Operator = { fg = colors.operator },
    Keyword = { fg = colors.keyword, bold = true },
    Exception = { fg = colors.error, bold = true },
    PreProc = { fg = colors.keyword },
    Include = { fg = colors.keyword },
    Define = { fg = colors.keyword },
    Macro = { fg = colors.keyword },
    PreCondit = { fg = colors.keyword },
    Type = { fg = colors.type },
    StorageClass = { fg = colors.type },
    Structure = { fg = colors.type },
    Typedef = { fg = colors.type },
    Special = { fg = colors.link },
    SpecialChar = { fg = colors.link },
    Tag = { fg = colors.link },
    Delimiter = { fg = colors.muted },
    SpecialComment = { fg = colors.muted, italic = true },
    Debug = { fg = colors.error },
    Underlined = { fg = colors.link, underline = true },
    Error = { fg = colors.error, bold = true },
    Todo = { fg = colors.warning, bold = true },
    Title = { fg = colors.text, bold = true },
    DiagnosticError = { fg = colors.error },
    DiagnosticWarn = { fg = colors.warning },
    DiagnosticInfo = { fg = colors.link },
    DiagnosticHint = { fg = colors.type },
    DiagnosticOk = { fg = colors.success },
    DiagnosticUnderlineError = { sp = colors.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = colors.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = colors.link, undercurl = true },
    DiagnosticUnderlineHint = { sp = colors.type, undercurl = true },
    WarningMsg = { fg = colors.warning },
    ErrorMsg = { fg = colors.error },
    ["@comment"] = { fg = colors.muted, italic = true },
    ["@string"] = { fg = colors.string },
    ["@character"] = { fg = colors.string },
    ["@number"] = { fg = colors.number },
    ["@boolean"] = { fg = colors.number },
    ["@constant"] = { fg = colors.constant },
    ["@constant.builtin"] = { fg = colors.constant },
    ["@variable"] = { fg = colors.variable },
    ["@variable.builtin"] = { fg = colors.constant },
    ["@parameter"] = { fg = colors.variable },
    ["@field"] = { fg = colors.variable },
    ["@property"] = { fg = colors.variable },
    ["@function"] = { fg = colors.func, bold = true },
    ["@function.builtin"] = { fg = colors.func, bold = true },
    ["@method"] = { fg = colors.func, bold = true },
    ["@constructor"] = { fg = colors.type },
    ["@keyword"] = { fg = colors.keyword, bold = true },
    ["@conditional"] = { fg = colors.keyword, bold = true },
    ["@repeat"] = { fg = colors.keyword, bold = true },
    ["@operator"] = { fg = colors.operator },
    ["@type"] = { fg = colors.type },
    ["@type.builtin"] = { fg = colors.type },
    ["@attribute"] = { fg = colors.type },
    ["@tag"] = { fg = colors.link },
    ["@punctuation.delimiter"] = { fg = colors.muted },
    ["@punctuation.bracket"] = { fg = colors.muted },
    ["@markup.link"] = { fg = colors.link, underline = true },
    ["@markup.heading"] = { fg = colors.keyword, bold = true },
    ["@markup.strong"] = { fg = colors.text, bold = true },
    ["@markup.italic"] = { fg = colors.text, italic = true },
    TelescopeNormal = { fg = colors.text, bg = colors.surface },
    TelescopeBorder = { fg = colors.border, bg = colors.surface },
    TelescopePromptNormal = { fg = colors.text, bg = colors.surface },
    TelescopePromptBorder = { fg = colors.link, bg = colors.surface },
    TelescopePromptTitle = { fg = colors.background, bg = colors.link, bold = true },
    TelescopePreviewTitle = { fg = colors.background, bg = colors.success, bold = true },
    TelescopeResultsTitle = { fg = colors.background, bg = colors.visited, bold = true },
    TelescopeSelection = { fg = colors.text, bg = colors.selection },
    TelescopeSelectionCaret = { fg = colors.active, bg = colors.selection },
    TelescopeMatching = { fg = colors.active, bold = true },
    TelescopeMultiSelection = { fg = colors.type, bg = colors.selection, bold = true },
    NeoTreeNormal = { fg = colors.text, bg = colors.background },
    NeoTreeNormalNC = { fg = colors.text, bg = colors.background },
    NeoTreeNormalFloat = { fg = colors.text, bg = colors.surface },
    NeoTreeEndOfBuffer = { fg = colors.muted, bg = colors.background },
    NeoTreeWinSeparator = { fg = colors.border, bg = colors.background },
    NeoTreeFileName = { fg = colors.text },
    NeoTreeDirectoryName = { fg = colors.link },
    NeoTreeDirectoryIcon = { fg = colors.link },
    NeoTreeRootName = { fg = colors.active, bold = true },
    NeoTreeIndentMarker = { fg = colors.border },
    NeoTreeExpander = { fg = colors.muted },
    NeoTreeDimText = { fg = colors.muted },
    NeoTreeFadeText1 = { fg = colors.muted },
    NeoTreeFadeText2 = { fg = colors.muted },
    NeoTreeDotfile = { fg = colors.muted },
    NeoTreeModified = { fg = colors.warning },
    NeoTreeMessage = { fg = colors.text, bg = colors.surface },
    MiniClueBorder = { fg = colors.border, bg = colors.surface },
    MiniClueTitle = { fg = colors.link, bg = colors.surface, bold = true },
    MiniClueDescGroup = { fg = colors.type, bg = colors.surface },
    MiniClueDescSingle = { fg = colors.text, bg = colors.surface },
    MiniClueNextKey = { fg = colors.active, bg = colors.surface, bold = true },
    MiniClueNextKeyWithPostkeys = { fg = colors.success, bg = colors.surface },
    MiniClueSeparator = { fg = colors.border, bg = colors.surface },
    BufferLineFill = { bg = colors.background },
    BufferLineBackground = { fg = colors.muted, bg = colors.surface },
    BufferLineBufferVisible = { fg = colors.text, bg = colors.surface },
    BufferLineBufferSelected = { fg = colors.text, bg = colors.background, bold = true },
    BufferLineTab = { fg = colors.muted, bg = colors.surface },
    BufferLineTabSelected = { fg = colors.text, bg = colors.background, bold = true },
    BufferLineTabClose = { fg = colors.error, bg = colors.surface },
    BufferLineCloseButton = { fg = colors.muted, bg = colors.surface },
    BufferLineCloseButtonSelected = { fg = colors.error, bg = colors.background },
    BufferLineIndicatorSelected = { fg = colors.active, bg = colors.background },
    BufferLineModified = { fg = colors.success, bg = colors.surface },
    BufferLineModifiedSelected = { fg = colors.success, bg = colors.background },
    BufferLineSeparator = { fg = colors.border, bg = colors.surface },
    BufferLineSeparatorVisible = { fg = colors.border, bg = colors.surface },
    BufferLineSeparatorSelected = { fg = colors.border, bg = colors.background },
    BufferLineOffsetSeparator = { fg = colors.border, bg = colors.background },
    FloatTitle = { fg = colors.link, bg = colors.surface, bold = true },
    GitSignsAdd = { fg = colors.success, bg = colors.surface },
    GitSignsAddLn = { fg = colors.success, bg = colors.surface },
    GitSignsAddInline = { fg = colors.background, bg = colors.success, bold = true },
    GitSignsChange = { fg = colors.warning, bg = colors.surface },
    GitSignsChangeLn = { fg = colors.warning, bg = colors.surface },
    GitSignsChangeInline = { fg = colors.background, bg = colors.warning, bold = true },
    GitSignsDelete = { fg = colors.error, bg = colors.surface },
    GitSignsDeleteLn = { fg = colors.error, bg = colors.surface },
    GitSignsDeleteInline = { fg = colors.background, bg = colors.error, bold = true },
    GitSignsUntracked = { fg = colors.link, bg = colors.surface },
    GitSignsUntrackedLn = { fg = colors.link, bg = colors.surface },
    GitSignsUntrackedInline = { fg = colors.background, bg = colors.link, bold = true },
    MiniStarterCurrent = { fg = colors.text, bg = colors.selection, bold = true },
    MiniStarterFooter = { fg = colors.link },
    MiniStarterHeader = { fg = colors.link, bold = true },
    MiniStarterInactive = { fg = colors.muted, italic = true },
    MiniStarterItem = { fg = colors.text },
    MiniStarterItemBullet = { fg = colors.constant },
    MiniStarterItemPrefix = { fg = colors.error, bold = true },
    MiniStarterSection = { fg = colors.constant },
    MiniStarterQuery = { fg = colors.success, bold = true },
    MiniSurround = { fg = colors.background, bg = colors.active, bold = true },
    RenderMarkdownBullet = { fg = colors.keyword },
    RenderMarkdownChecked = { fg = colors.success },
    RenderMarkdownCode = { bg = colors.surface },
    RenderMarkdownCodeInline = { fg = colors.text },
    RenderMarkdownDash = { fg = colors.keyword },
    RenderMarkdownH1 = { fg = colors.number },
    RenderMarkdownH1Bg = { bg = colors.surface },
    RenderMarkdownH2 = { fg = colors.warning },
    RenderMarkdownH2Bg = { bg = colors.surface },
    RenderMarkdownH3 = { fg = colors.success },
    RenderMarkdownH3Bg = { bg = colors.surface },
    RenderMarkdownH4 = { fg = colors.type },
    RenderMarkdownH4Bg = { bg = colors.surface },
    RenderMarkdownH5 = { fg = colors.link },
    RenderMarkdownH5Bg = { bg = colors.surface },
    RenderMarkdownH6 = { fg = colors.constant },
    RenderMarkdownH6Bg = { bg = colors.surface },
    RenderMarkdownTodo = { fg = colors.warning, bold = true },
    RenderMarkdownUnchecked = { fg = colors.warning },
}

for group, highlightspec in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, highlightspec)
end

vim.g.colors_name = theme.colorscheme
